### ISSUE TITLE
Please update to go-sonnet version v0.14.0.

### ISSUE THREAD

**Issue by nightlyone** [bitnami/kubecfg#277]
We just ran into a major performance issue while generating a few number of configurations via set logic. 

The root cause of our issues was missing caching of already computed ASTs in the jsonnet library.
And described in more detail at https://databricks.com/blog/2018/10/12/writing-a-faster-jsonnet-compiler.html

This has been fixed in v0.14.0 as mentioned in https://github.com/google/jsonnet/releases/tag/v0.14.0 (also linked in https://github.com/google/go-jsonnet/releases/tag/v0.14.0 )

So please consider an update in the go.mod file and do a release, if you agree.

**Comment by mkmik** [comment]
released in https://github.com/bitnami/kubecfg/releases/tag/v0.14.0 :-)

**Comment by nightlyone** [comment]
Many thanks for the quick fix! :heart_eyes:
