### ISSUE TITLE
Error go getting kubecfg

### ISSUE THREAD

**Issue by kskewes** [bitnami/kubecfg#285]
Tried install per docs. 

```
$ go get github.com/bitnami/kubecfg
go get: github.com/bitnami/kubecfg@v0.15.1 requires
        contrib.go.opencensus.io/exporter/ocagent@v0.4.6 requires
        github.com/census-instrumentation/opencensus-proto@v0.1.0-0.20181214143942-ba49f56771b8: invalid pseudo-version: version before v0.1.0 would have negative patch number

$ go version
go version go1.13.8 linux/amd64
```

0.15.1 binary from Github Releases release works fine though

**Comment by camh-anz** [comment]
This is due to https://github.com/Azure/go-autorest/issues/449.

I guess it could be resolved by updating the contrib.go.opencensus.io/exporter/ocagent module dependency in this (kubecfg) repo?

**Comment by camh-** [comment]
This same problem has been raised against other repos that use opencensus - e.g. https://github.com/Azure/go-autorest/issues/449

I think kubecfg just needs to update its `contrib.go.opencensus.io/exporter/ocagent` dependency and cut a new release.
