### ISSUE TITLE
Needs implementation for --ext-code and --tla-code

### ISSUE THREAD

**Issue by GauntletWizard** [bitnami/kubecfg#63]
These were on my backburner, because I thought I didn't need them, but I ran into a situation today that required it. This issue is mostly for my benefit (I'll try to whip one out this weekend)

**Comment by seh** [comment]
I too noticed that these are missing (along with their "file" variants). @anguslees, is their omission deliberate, or do you think it would be useful to have these available in _kubecfg_?
